CY-Library : Main.o Borrow.o Visual.o Account.o Books.o 
	gcc -o CY-Library Main.o Borrow.o Visual.o Account.o Books.o 

Main.o : ./Source/Main.c
	gcc -o Main.o -c ./Source/Main.c

Books.o : ./Source/Books.c
	gcc -o Books.o -c ./Source/Books.c

Account.o : ./Source/Account.c
	gcc -o Account.o -c ./Source/Account.c

Visual.o : ./Source/Visual.c
	gcc -o Visual.o -c ./Source/Visual.c

Borrow.o : ./Source/Borrow.c
	gcc -o Borrow.o -c ./Source/Borrow.c
